### PR TITLE
Return body chunks before boundary

### LINKED ISSUE #7: MultipartStream stuck on field
Hi there,

Just tried this crate up; it would be exactly what we'd need over at [rs-ipfs/rust-ipfs](https://github.com/rs-ipfs/rust-ipfs). Uploads tend to become stuck with high cpu usage as the part stream returns endlessly `Some(Ok(b""))`.

Sorry for the paste quality; was hoping to PR the fix but I am a bit lost. Test case can be appended to src/server.rs.

<details><summary>Overly large reproducer</summary>

```
    #[test]
    fn zero_read() {
        let input = b"\
----------------------------332056022174478975396798\r\n\
Content-Disposition: form-data; name=\"file\"\r\n\
Content-Type: application/octet-stream\r\n\
\r\n\
\r\n\
\r\n\
dolphin\n\
whale\r\n\
----------------------------332056022174478975396798--\r\n";

        let boundary = "--------------------------332056022174478975396798";

        let mut read = MultipartStream::new(boundary, ByteStream::new(input));

        let mut part = match block_on(read.next()).unwrap() {
            Ok(mf) => {
                assert_eq!(mf.name().unwrap(), "file");
                assert_eq!(mf.content_type().unwrap(), "application/octet-stream");
                mf
            }
            Err(e) => panic!("unexpected: {}", e),
        };

        let first = block_on(part.next()).unwrap().unwrap();

        // this should be b"dolphin\nwhale" (13 bytes, no trailing \n)
        // but it also contains the end boundary:
        // "\r\n\r\ndolphin\nwhale\r\n----------------------------332056022174478975396798--\r\n"
        print!("first: ");
        for b in first.as_ref() {
            print!("{:02x}", b);
        }
        println!();
        println!("first: {:?}", String::from_utf8_lossy(first.as_ref()));

        // the stream is already exhausted, but this is Some(Ok(b""))
        // same for third; the part is now "stuck"
        let second = block_on(part.next());
        println!("second: {:02x?}", second); // this is empty

        let third = block_on(part.next());
        println!("third: {:02x?}", third); // this is empty

        let fourth = block_on(read.next());
        println!("fourth: {:02x?}", fourth.unwrap().unwrap()); // this is error ShouldPollField

        assert_eq!(first.len(), 8 + 5); // this is correct
    }
```
</details>

~Whoops, posted too early, editing this here in a sec :)~ Added.

I figure there is an issue detecting the final boundary. I've extracted the request body from wireshark so there might still be copy paste issues, but this at least demonstrates the "getting stuck" which definitely happens on https://github.com/rs-ipfs/rust-ipfs/pull/225.

### PR DESCRIPTION
**Pull request by koivunej**
Ended up making a lot of changes to help debugging this thing and while thinking about the issue and thus tried to clean up as much as possible. Still, quite a lot of changes remained:

 - the code now supports returning small chunks in the case of `\r` in the body (see #7)
 - inner stream is advanced only when necessary (loop + State boolean)
 - few new error cases which were previously silently ignored (test cases adjusted accordingly)

Any ideas welcome to combat the big change. I was thinking about separating a "tokenizer" but that would had been even a bigger change.

Changes considered but not included or removed while cleaning up:

 - removal of `anyhow` usage
 - replacing Vec buffer with BytesMut
 - testing with arbitary sized chunks

Fixes #7. CC: @cetra3.

### CODE REVIEW

File: src/server.rs [hunk 1]
```diff
@@ -261,13 +258,14 @@ fn get_headers(buffer: &[u8]) -> Result<HeaderMap<HeaderValue>, MultipartError>
...
-                HeaderValue::from_bytes(header.value).map_err(|_| MultipartError::InvalidHeader)?,
-            );
+        if header.name == "" {
+            continue;
         }
+        header_map.insert(
+            HeaderName::from_bytes(header.name.as_bytes())
+                .map_err(|_| MultipartError::InvalidHeader)?,
+            HeaderValue::from_bytes(header.value).map_err(|_| MultipartError::InvalidHeader)?,
+        );
```
Comment (koivunej) [inline src/server.rs]: Extra, I'll clean this out.

**Comment by koivunej** [comment]
Did some initial testing with all subslices chunks (from len 1..(input size)) and the test cases which I've modified locally seem to behave nicely. Thinking of firing off another PR regarding those.

File: src/server.rs [hunk 2]
```diff
@@ -550,7 +576,13 @@ mod tests {
                 Content-Type: text/plain";
         let mut read = MultipartParser::new("AaB03x", ByteStream::new(input));
 
-        assert!(block_on(read.next()).is_none());
+        let ret = block_on(read.next());
+
+        assert!(
```
Comment (cetra3) [inline src/server.rs]: Rather than casting to a String, these can be rewritten as:

```rust
        assert!(matches!(
            ret,
            Some(Err(MultipartError::EOFWhileReadingHeaders))
        ),);
```

File: src/server.rs [hunk 3]
```diff
@@ -622,4 +660,48 @@ mod tests {
             }
         }
     }
+
+    #[test]
+    fn zero_read() {
+        use bytes::{BufMut, BytesMut};
+
+        let input = b"\
```
Comment (cetra3) [inline src/server.rs]: It may be a bit neater indenting this block to keep it inline with the other input tests

**Comment by cetra3** [comment]
All looks good!  I have added in a couple of comments just to clean it up a little bit.

**Comment by koivunej** [comment]
@cetra3 I cannot see any other comments from you except [this one](https://github.com/cetra3/mpart-async/pull/8#issuecomment-655198214) ... Perhaps the comments are pending review completion?

**Comment by cetra3** [comment]
Gets me every time

File: src/server.rs (hunk 2 above)
Comment (koivunej) [reply src/server.rs]: The last two are only used for the message if the assertion fails. My proposed version would produce:

```
thread 'server::tests::unfinished_second_header' panicked at 'Some(Err(EOFWhileReadingHeaders))', src/server.rs:613:9
```

In the message you can see the _actual_ value. Removing those would instead give:

```
thread 'server::tests::unfinished_second_header' panicked at 'assertion failed: false && matches!(ret, Some(Err(MultipartError :: EOFWhileReadingHeaders)))', src/server.rs:613:9
```

Now the message would only contain the _expected_ value. (The `false && ` prefix was of course for illustration only) :)

File: src/server.rs (hunk 3 above)
Comment (koivunej) [reply src/server.rs]: Good point, done!

File: src/server.rs (hunk 2 above)
Comment (koivunej) [reply src/server.rs]: Let me know if you'd still like the formatting of the actual value to be removed; I don't have strong feelings for this but I've had to debug some of my own `assert!(matches!(...))` failures in the past which is why I prefer to not lose the _actual_ value :)

Comment (cetra3) [reply src/server.rs]: I see! Yeah I'd still prefer it to be the concrete type as it has greater equality

Comment (koivunej) [reply src/server.rs]: I feel like I've managed to miscommunicate the used feature here :) I removed the messages. Marking as resolved.

**Comment by koivunej** [comment]
EDIT: commented on the wrong tab :D apologies.
